<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class InfgadprocTestParts extends Model
{
    protected $table = 'infgadproc_test_parts';
    protected $fillable = [
        'uuid','winadadeba','siis_var','categoria'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
