<?php


namespace TestCMS\Models;


use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class InfgadprocTest extends Model
{
    use Translatable;
    protected $table = 'infgadproc_test';
    public $translationModel = 'TestCMS\Models\InfgadprocTestTranslations';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];
    protected $fillable = [
        'uuid','row','time','timetest','proc'
    ];
    public function Infgadproctest($uuid)
    {
//        dump($uuid);
        return $this->belongsToMany(InfgadprocTest::class, 'infgadproc_test_to_any', 'empti', 'infgadproc_test', 'uuid', 'uuid')
            ->withPivot('row_uuid','infgadproc_test')->where('infgadproc_test', '=', $uuid);
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
