<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class LewsgadTestParts extends Model
{
    protected $table = 'lewsgad_test_parts';
    protected $fillable = [
        'uuid','zeda','qveda','varinat'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
