<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Local extends Model
{
    protected $table = 'locals';
    protected $fillable = [
        'uuid', 'local', 'original_name', 'latin_name', 'is_active', 'is_default'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            $model->uuid = Uuid::uuid4();
        });
    }
}
