<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class MentalRotaciaTestParts extends Model
{
    protected $table = 'mental_rotacia_test_parts';
    protected $fillable = [
        'uuid','testaso','gradusi','revers'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }

}
