<?php


namespace TestCMS\Models;


use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class MentalRotaciaTest extends Model
{
    use Translatable;
    protected $table = 'mental_rotacia_test';
    public $translationModel = 'TestCMS\Models\MentalRotaciaTestTranslations';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];

    protected $fillable = [
        'uuid','rotatestart','rotatefinish','rotaterange','time','timefull','proc','rov'
    ];

    public function MentalCompare($uuid)
    {
//        dump($uuid);
        return $this->belongsToMany(MentalRotaciaTest::class, 'mental_rotacia_test_to_any', 'empti', 'mental_rotacia_test', 'uuid', 'uuid')
            ->withPivot('row_uuid','mental_rotacia_test')->where('mental_rotacia_test', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
