<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class MentalRotaciaTestPasux extends Model
{
    protected $table = 'mental_rotacia_test_pasux';
    protected $fillable = [
        'uuid','testaso','gradusi','revers','momxpasux','pasuxdro','upasuxtuara','sworipasux','xgerdz','ygerdz','testuuid'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
