<?php


namespace TestCMS\Models;


use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Menu extends Model
{
    use Translatable;
    protected $table = 'menu';
    protected $fillable = [
        'uuid', 'sort', 'target', 'type', 'parent_id'
    ];
    public $translatedAttributes = [
        'name','local'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }

}
