<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class PerceftCompareTestPasux extends Model
{
    protected $table = 'perceft_compare_test_pasux';
    protected $fillable = [
        'uuid','persbig','persbigpass','momxpasux','pasuxdro','upasuxtuara','sworipasux','xgerdz','ygerdz','testuuid','seqtorei'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
