<?php


namespace TestCMS\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class PerceftCompareTest extends Model
{
    use Translatable;
    protected $table = 'perceft_compare_test';
    public $translationModel = 'TestCMS\Models\PerceftCompareTestTranslations';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];
    protected $fillable = [
        'uuid','raodenoba','swori','timetest','fulltime','proc'
    ];
    public function PerceftCompare($uuid)
    {
//        dd($uuid);
        return $this->belongsToMany(PerceftCompareTest::class, 'perceft_compare_test_to_any', 'empti', 'row_uuid', 'uuid', 'uuid')
            ->withPivot('row_uuid','perceft_compare_test_uuid')->where('row_uuid', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
