<?php


namespace TestCMS\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Post extends Model
{
    use Translatable;
    protected $table = 'post';
    protected $fillable = [
        'uuid','is_active','is_featured','is_comment_on','type','motc','full'
    ];
    public $translatedAttributes = [
        'meta_title','meta_description','og_title','og_description','title','description','slug','locale'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
