<?php


namespace TestCMS\Models;


use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class ReaqciYuradgTest extends Model
{
    use Translatable;
    protected $table = 'reaqci_yuradg_test';
    public $translationModel = 'TestCMS\Models\ReaqciYuradgTestTranslations';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];
    protected $fillable = [
        'uuid','raodenoba','pirveeliraod','meoreraod','mesamevar','time','timefull','proc'
    ];

    public function ReaqciCompare($uuid)
    {
//        dd($uuid);
        return $this->belongsToMany(ReaqciYuradgTest::class, 'reaqci_yuradg_test_to_any', 'empti', 'reaqci_yuradg_test_uuid', 'uuid', 'uuid')
            ->withPivot('row_uuid','reaqci_yuradg_test_uuid')->where('reaqci_yuradg_test_uuid', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
