<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class ReaqciYuradgTestPasux extends Model
{
    protected $table = 'reaqci_yuradg_test_pasux';
    protected $fillable = [
        'uuid','pirveliaso','pirvelgilak','meoreaso','meoregilak','mesameaso','mesamegilak','meotxeaso','meotxegilak','momxpasux','pasuxdro','upasuxtuara','sworipasux','xgerdz','ygerdz','testuuid','altraod'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
