<?php


namespace TestCMS\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class RegisterUser extends Model
{
    use Translatable;
    protected $table = 'register_user';
    protected $fillable = [
      'uuid','user','password','status','reg_user'
    ];
    public $translatedAttributes = [
        'name','lname','email','locale'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }

    public function Registertoani($id){
        return $this->belongsToMany(RegisterUser::class,'register_user_to_any','empti','register_user_uuid','uuid','uuid')
            ->withPivot('row_uuid')->where('register_user.id','=',$id);
    }

}
