<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SelectionTestPasux extends Model
{
    protected $table = 'selection_test_pasux';
    protected $fillable = [
        'uuid','variant','dashoreba','pirveliaso','meoreaso','momxpasux','pasuxdro','upasuxtuara','sworipasux','xgerdz','ygerdz','testuuid'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
