<?php


namespace TestCMS\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SelectionTest extends Model
{
    use Translatable;
    protected $table = 'selection_test';
    public $translationModel = 'TestCMS\Models\SelectionTestTranslations';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];

    protected $fillable = [
        'uuid','row','first','time','timetest','proc'
    ];

    public function Selectiontoani($uuid)
    {
//        dd($uuid);
        return $this->belongsToMany(SelectionTest::class, 'selection_test_to_any', 'empti', 'selection_test_uuid', 'uuid', 'uuid')
            ->withPivot('row_uuid')->where('selection_test_uuid', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
