<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SelectionTestParts extends Model
{
    protected $table = 'selection_test_parts';
    protected $fillable = [
      'uuid','variant','dashoreba','pirveliaso','meoreaso'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
