<?php


namespace TestCMS\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SignalDetecTest extends Model
{
    use Translatable;
    protected $table = 'signal_detec_test';
    public $translationModel = 'TestCMS\Models\SignalDetecTestTranslation';
    public $translatedAttributes = [
        'title', 'desc', 'locale','defic'
    ];
    protected $fillable = [
        'uuid', 'time', 'row', 'true', 'false','chdilistart','chdilifinish','sworipasx_raod', 'timetest','proc'
    ];

    public function Signaltoani($uuid)
    {
//        dd($uuid);
        return $this->belongsToMany(SignalDetecTest::class, 'signal_detec_test_to_any', 'type', 'Signal_detec_test_uuid', 'uuid', 'uuid')
            ->withPivot('row_uuid')->where('Signal_detec_test_uuid', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
