<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SignalDetecTestToAny extends Model
{
    protected $table = 'signal_detec_test_to_any';
    public $timestamps = false;
    protected $fillable = [
      'Signal_detec_test_uuid','row_uuid','type'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
