<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SignalDetecTestParts extends Model
{

    protected $table = 'signal_detec_test_parts';
    protected $fillable = [
        'uuid','Correct','Wrong','arrangement','Quantity','procenti'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
