<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class StrupEfeqtTestPasux extends Model
{
    protected $table = 'strup_efeqt_test_pasux';
    protected $fillable = [
        'uuid','color','text','kebord','momxpasux','pasuxdro','upasuxtuara','sworipasux','xgerdz','ygerdz','testuuid','kofiguration'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
