<?php


namespace TestCMS\Models;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class StrupEfeqtTestParts extends Model
{
    protected  $table = 'strup_efeqt_test_parts';
    protected $fillable = [
      'uuid','color','text','kebord','kofiguration'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            $model->uuid = Uuid::uuid4();
        });
    }
}
